[package]
name = "particles"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
license = "MIT"
repository = "https://github.com/losfair/particles-rs"

[lib]
name = "particles"
crate-type = ["cdylib"]

[dependencies]
